src/Detail/index.js
https://github.com/CodeandoMexico/covid-estados/issues/4
=> #4 Ocultar el titulo Hazte la prueba en línea

src/Detail/index.js, src/Detail/index.scss
Corregido acentos en cuado de atención a líneas locales
Corregido números telefónicos en varias líneas
=> Paginas de estados: Múltiples números de teléfono en distintas líneas

src/Components/components.scss, src/Components/index.js, src/Detail/index.js
=> Correccion de leyendas confirmados/activos/sospechsos

src/Components/components.scss, src/Components/index.js, src/Detail/index.js, src/Detail/index.scss, src/Home/Home.scss, src/Home/index.jsx
Nuevo componente del Dropdown de estados para reutilizarlo en la vista de Details.
https://github.com/CodeandoMexico/covid-estados/issues/2
=> Te interesa información de otro estado (Dropdown)

src/Components/components.scss, src/Components/index.js, src/Detail/index.js, src/Detail/index.scss
@almarngl a esto re te refieres?
Estoy resolviendo el comentario de @almarngl en el issue:
https://github.com/CodeandoMexico/covid-estados/issues/4
Se esta completando la sección de  Medidas oficiales conforme al diseño y se creo un nuevo componente <Badge>.
https://github.com/CodeandoMexico/covid-estados/issues/3
=> Hide Sections y Medidas oficiales

src/About/About.scss
ola, vengo aki a dar mi humilde commit si me lo acecta de fabor
=> closes #16

src/Components/components.scss, src/Detail/index.js, src/Detail/index.scss
=> closes #24

src/About/About.scss
arreglando los desarreglos que hice, ansory
=> fixes distribution on about page

src/Detail/index.js
=> Link boton "conoce mas"

package.json, src/App.js, yarn.lock
=> Add history

src/App.js, src/Detail/index.js, src/Footer/index.jsx, src/NavMain/index.jsx, src/utils/GoogleAnalytics.js
Se actualiza GA para no setearlo  y sea actualizan Urls
=> Update GA and urls

src/actions/index.js
=> Fixed URLs for states. :gear:

src/Components/components.scss, src/Detail/InformationDetail.js, src/Detail/index.js, src/Detail/index.scss
=> arregla botón gordo y código de color gris para sin informacion

src/Components/components.scss, src/Detail/InformationDetail.js, src/Detail/index.js, src/Detail/index.scss
Reverts CodeandoMexico/covid-estados#50
=> Revert "arregla botón gordo y código de color gris para sin informacion"

src/Detail/index.js, src/Detail/index.scss
=> distribución de la tarjeta de teléfonos

src/Detail/index.js
Agrega links a los telefonos.
Closes #63
=> Links telefonicos

src/Detail/InformationDetail.js
Los links faltantes
Closes #63
=> Otros links

src/Detail/index.js
se actualiza a una url donde se pueda descargar directamente el CSV del servicio de Airtable
=> update url download csv

.github/workflows/node.js.yml, README.md
Build automatizado con cada push y pull request.
=> Continous Integration

src/About/index.jsx, src/Detail/InformationDetail.js
Agregué para que al entrar a About (Sobre el proyecto) scrollee hasta arriba. Al entrar desde algún estado en el footer se mostraba hasta abajo.
También modifiqué unos class a className (React) por los warning.
Este es mi primer PR, me avisan por cualquier feedback o algo :)
=> Scroll to top on About

public/index.html, src/Detail/InformationDetail.js, src/Detail/config.js
=>  Merge develop to master

src/Detail/Symptoms.js
Del issue #71 
Agregué el mensaje y también ya no manda a la nueva pestaña al darle clic.
Anexo como se ve.
=> Message on SMS

src/Detail/InformationDetail.js
Desde el issue #72 
Se agrega la información desde la columna otros, que puede depender en ser link o teléfonos.
=> Elements from column Otros on InformationDetail
